// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFmnsQyQzL3P8c08OCU0H6JyEQ0V7JNX0',
    appId: '1:415572090148:web:4da8de959cd36d668f27b1',
    messagingSenderId: '415572090148',
    projectId: 'abcmobileapp-csci4311',
    authDomain: 'abcmobileapp-csci4311.firebaseapp.com',
    storageBucket: 'abcmobileapp-csci4311.firebasestorage.app',
    measurementId: 'G-PXY09N1JYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp470sxAmSmjhY-mH2gU3Y8LxEL0LwfXI',
    appId: '1:415572090148:android:1cc50d2cc56a1f898f27b1',
    messagingSenderId: '415572090148',
    projectId: 'abcmobileapp-csci4311',
    storageBucket: 'abcmobileapp-csci4311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcVRxXB4KunXMzQ5j_cmIkmQLhxUJDJJU',
    appId: '1:415572090148:ios:7e1ff0778c31d9a68f27b1',
    messagingSenderId: '415572090148',
    projectId: 'abcmobileapp-csci4311',
    storageBucket: 'abcmobileapp-csci4311.firebasestorage.app',
    iosBundleId: 'com.example.abcmobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcVRxXB4KunXMzQ5j_cmIkmQLhxUJDJJU',
    appId: '1:415572090148:ios:7e1ff0778c31d9a68f27b1',
    messagingSenderId: '415572090148',
    projectId: 'abcmobileapp-csci4311',
    storageBucket: 'abcmobileapp-csci4311.firebasestorage.app',
    iosBundleId: 'com.example.abcmobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFmnsQyQzL3P8c08OCU0H6JyEQ0V7JNX0',
    appId: '1:415572090148:web:0b8fb1c62f4220378f27b1',
    messagingSenderId: '415572090148',
    projectId: 'abcmobileapp-csci4311',
    authDomain: 'abcmobileapp-csci4311.firebaseapp.com',
    storageBucket: 'abcmobileapp-csci4311.firebasestorage.app',
    measurementId: 'G-45RSEY7CVT',
  );
}
